# Generated by Django 5.0.4 on 2024-05-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestellung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrihedInvoice',
            fields=[
                ('invoice_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'verbose_name_plural': 'Grihed Invoices',
            },
        ),
        migrations.CreateModel(
            name='GrihedInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_items', to='bestellung.beveragecrate')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='rechnungen.grihedinvoice')),
                ('purchase_price', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_items', to='bestellung.grihedprice')),
                ('sale_price', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_items', to='bestellung.saleprice')),
            ],
            options={
                'verbose_name_plural': 'Grihed Invoice Items',
                'unique_together': {('invoice', 'beverage')},
            },
        ),
    ]
