# Generated by Django 5.0.6 on 2024-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rechnungen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grihedinvoiceitem',
            name='name',
        ),
    ]
